aws:
  providers:
    iam:
      version: "v0.41.0"
      controllerConfig: {}
    s3:
      version: "v0.41.0"
      controllerConfig: {}
    dynamodb:
      version: "v0.41.0"
      controllerConfig: {}
    lambda:
      version: "v0.41.0"
      controllerConfig: {}
    sqs:
      version: "v0.41.0"
      controllerConfig: {}
    apigateway:
      version: "v0.41.0"
      controllerConfig: {}
    cognito:
      version: "v0.41.0"
      controllerConfig: {}
    bedrock:
      version: "v0.41.0"
      controllerConfig: {}
    cloudfront:
      version: "v0.41.0"
      controllerConfig: {}
    secretsmanager:
      version: "v0.41.0"
      controllerConfig: {}
