apiVersion: cognitoidp.aws.upbound.io/v1beta1
kind: UserPool
metadata:
  name: {{ include "serverless-pdf-chat.fullname" . }}-user-pool
  labels:
    {{- include "serverless-pdf-chat.labels" . | nindent 4 }}
spec:
  forProvider:
    region: {{ .Values.aws.region }}
    name: {{ default (include "serverless-pdf-chat.fullname" .) .Values.aws.cognito.userPool.name }}
    autoVerifiedAttributes:
      {{- range .Values.aws.cognito.userPool.autoVerifiedAttributes }}
      - {{ . }}
      {{- end }}
    usernameAttributes:
      {{- range .Values.aws.cognito.userPool.usernameAttributes }}
      - {{ . }}
      {{- end }}
    adminCreateUserConfig:
      allowAdminCreateUserOnly: {{ .Values.aws.cognito.userPool.adminCreateUserConfig.allowAdminCreateUserOnly }}
    passwordPolicy:
      minimumLength: {{ .Values.aws.cognito.userPool.passwordPolicy.minimumLength }}
      requireLowercase: {{ .Values.aws.cognito.userPool.passwordPolicy.requireLowercase }}
      requireNumbers: {{ .Values.aws.cognito.userPool.passwordPolicy.requireNumbers }}
      requireSymbols: {{ .Values.aws.cognito.userPool.passwordPolicy.requireSymbols }}
      requireUppercase: {{ .Values.aws.cognito.userPool.passwordPolicy.requireUppercase }}
  providerConfigRef:
    name: {{ .Values.aws.providerConfigName }}

---
apiVersion: cognitoidp.aws.upbound.io/v1beta1
kind: UserPoolClient
metadata:
  name: {{ include "serverless-pdf-chat.fullname" . }}-user-pool-client
  labels:
    {{- include "serverless-pdf-chat.labels" . | nindent 4 }}
spec:
  forProvider:
    region: {{ .Values.aws.region }}
    # Use a selector to reference the user pool
    userPoolIdSelector:
      matchLabels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ include "serverless-pdf-chat.name" . }}
    name: {{ default (include "serverless-pdf-chat.fullname" .) .Values.aws.cognito.userPoolClient.name }}
    generateSecret: {{ .Values.aws.cognito.userPoolClient.generateSecret }}
  providerConfigRef:
    name: {{ .Values.aws.providerConfigName }}
