{{- if .Values.aws.dynamodb }}
{{- if .Values.aws.dynamodb.documentTable }}
---
apiVersion: dynamodb.aws.upbound.io/v1beta1
kind: Table
metadata:
  name: {{ include "serverless-pdf-chat.resourceName" (dict "Values" .Values "name" "documents") }}
  labels:
    {{- include "serverless-pdf-chat.labels" $ | nindent 4 }}
  {{- with $.Values.tags }}
  tags:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  forProvider:
    region: {{ .Values.aws.region }}
    {{- if .Values.aws.dynamodb.documentTable.name }}
    tableName: {{ .Values.aws.dynamodb.documentTable.name }}
    {{- else }}
    tableName: {{ include "serverless-pdf-chat.resourceName" (dict "Values" .Values "name" "documents") }}
    {{- end }}
    billingMode: {{ $.Values.aws.dynamodb.billingMode }}
    attribute:
    {{- range .Values.aws.dynamodb.documentTable.attributeDefinitions }}
    - name: {{ .attributeName }}
      type: {{ .attributeType }}
    {{- end }}
    hashKey: {{ .Values.aws.dynamodb.documentTable.hashKey }}
    {{- if .Values.aws.dynamodb.documentTable.rangeKey }}
    rangeKey: {{ .Values.aws.dynamodb.documentTable.rangeKey }}
    {{- end }}
  providerConfigRef:
    name: {{ $.Values.aws.providerConfigName }}
{{- end }}

{{- if .Values.aws.dynamodb.memoryTable }}
---
apiVersion: dynamodb.aws.upbound.io/v1beta1
kind: Table
metadata:
  name: {{ include "serverless-pdf-chat.resourceName" (dict "Values" .Values "name" "memory") }}
  labels:
    {{- include "serverless-pdf-chat.labels" $ | nindent 4 }}
  {{- with $.Values.tags }}
  tags:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  forProvider:
    region: {{ .Values.aws.region }}
    {{- if .Values.aws.dynamodb.memoryTable.name }}
    tableName: {{ .Values.aws.dynamodb.memoryTable.name }}
    {{- else }}
    tableName: {{ include "serverless-pdf-chat.resourceName" (dict "Values" .Values "name" "memory") }}
    {{- end }}
    billingMode: {{ $.Values.aws.dynamodb.billingMode }}
    attribute:
    {{- range .Values.aws.dynamodb.memoryTable.attributeDefinitions }}
    - name: {{ .attributeName }}
      type: {{ .attributeType }}
    {{- end }}
    hashKey: {{ .Values.aws.dynamodb.memoryTable.hashKey }}
    {{- if .Values.aws.dynamodb.memoryTable.rangeKey }}
    rangeKey: {{ .Values.aws.dynamodb.memoryTable.rangeKey }}
    {{- end }}
  providerConfigRef:
    name: {{ $.Values.aws.providerConfigName }}
{{- end }}
{{- end }}
