{{- if .Values.aws.dynamodb -}}
{{- if .Values.aws.dynamodb.documentTable -}}
---
apiVersion: dynamodb.aws.upbound.io/v1beta1
kind: Table
metadata:
  name: {{ include "serverless-pdf-chat.resourceName" (dict "Values" .Values "name" "documents") }}
  labels:
    {{- include "serverless-pdf-chat.labels" $ | nindent 4 }}
  {{- with $.Values.tags }}
  tags:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  forProvider:
    region: {{ .Values.aws.region }}
    {{- if .Values.aws.dynamodb.documentTable.name }}
    tableName: {{ .Values.aws.dynamodb.documentTable.name }}
    {{- else }}
    tableName: {{ include "serverless-pdf-chat.resourceName" (dict "Values" .Values "name" "documents") }}
    {{- end }}
    billingMode: {{ $.Values.aws.dynamodb.billingMode }}
    attributeDefinitions:
    {{- range .Values.aws.dynamodb.documentTable.attributeDefinitions }}
    - attributeName: {{ .attributeName }}
      attributeType: {{ .attributeType }}
    {{- end }}
    keySchema:
    {{- range .Values.aws.dynamodb.documentTable.keySchema }}
    - attributeName: {{ .attributeName }}
      keyType: {{ .keyType }}
    {{- end }}
  providerConfigRef:
    name: {{ $.Values.aws.providerConfigName }}
{{- end }}

{{- if .Values.aws.dynamodb.memoryTable }}
---
apiVersion: dynamodb.aws.upbound.io/v1beta1
kind: Table
metadata:
  name: {{ include "serverless-pdf-chat.resourceName" (dict "Values" .Values "name" "memory") }}
  labels:
    {{- include "serverless-pdf-chat.labels" $ | nindent 4 }}
  {{- with $.Values.tags }}
  tags:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  forProvider:
    region: {{ .Values.aws.region }}
    {{- if .Values.aws.dynamodb.memoryTable.name }}
    tableName: {{ .Values.aws.dynamodb.memoryTable.name }}
    {{- else }}
    tableName: {{ include "serverless-pdf-chat.resourceName" (dict "Values" .Values "name" "memory") }}
    {{- end }}
    billingMode: {{ $.Values.aws.dynamodb.billingMode }}
    attributeDefinitions:
    {{- range .Values.aws.dynamodb.memoryTable.attributeDefinitions }}
    - attributeName: {{ .attributeName }}
      attributeType: {{ .attributeType }}
    {{- end }}
    keySchema:
    {{- range .Values.aws.dynamodb.memoryTable.keySchema }}
    - attributeName: {{ .attributeName }}
      keyType: {{ .keyType }}
    {{- end }}
  providerConfigRef:
    name: {{ $.Values.aws.providerConfigName }}
{{- end }}
{{- end }}
