{{- if .Values.aws.dynamodb }}
{{- if .Values.aws.dynamodb.documentTable }}
---
apiVersion: dynamodb.aws.upbound.io/v1beta1
kind: Table
metadata:
  name: {{ include "serverless-pdf-chat.resourceName" (dict "Values" .Values "name" "documents") }}
  labels:
    {{- include "serverless-pdf-chat.labels" $ | nindent 4 }}
spec:
  forProvider:
    region: {{ .Values.aws.region }}
    billingMode: {{ $.Values.aws.dynamodb.billingMode }}
    tags:
      {{- if .Values.aws.dynamodb.documentTable.name }}
      Name: {{ .Values.aws.dynamodb.documentTable.name }}
      {{- else }}
      Name: {{ include "serverless-pdf-chat.resourceName" (dict "Values" .Values "name" "documents") }}
      {{- end }}
      {{- with $.Values.tags }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
    attribute:
    {{- range .Values.aws.dynamodb.documentTable.attributeDefinitions }}
    - name: {{ .attributeName }}
      type: {{ .attributeType }}
    {{- end }}
    hashKey: {{ .Values.aws.dynamodb.documentTable.hashKey }}
    {{- if .Values.aws.dynamodb.documentTable.rangeKey }}
    rangeKey: {{ .Values.aws.dynamodb.documentTable.rangeKey }}
    {{- end }}
  providerConfigRef:
    name: {{ $.Values.aws.providerConfigName }}
{{- end }}

{{- if .Values.aws.dynamodb.memoryTable }}
---
apiVersion: dynamodb.aws.upbound.io/v1beta1
kind: Table
metadata:
  name: {{ include "serverless-pdf-chat.resourceName" (dict "Values" .Values "name" "memory") }}
  labels:
    {{- include "serverless-pdf-chat.labels" $ | nindent 4 }}
spec:
  forProvider:
    region: {{ .Values.aws.region }}
    billingMode: {{ $.Values.aws.dynamodb.billingMode }}
    tags:
      {{- if .Values.aws.dynamodb.memoryTable.name }}
      Name: {{ .Values.aws.dynamodb.memoryTable.name }}
      {{- else }}
      Name: {{ include "serverless-pdf-chat.resourceName" (dict "Values" .Values "name" "memory") }}
      {{- end }}
      {{- with $.Values.tags }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
    attribute:
    {{- range .Values.aws.dynamodb.memoryTable.attributeDefinitions }}
    - name: {{ .attributeName }}
      type: {{ .attributeType }}
    {{- end }}
    hashKey: {{ .Values.aws.dynamodb.memoryTable.hashKey }}
    {{- if .Values.aws.dynamodb.memoryTable.rangeKey }}
    rangeKey: {{ .Values.aws.dynamodb.memoryTable.rangeKey }}
    {{- end }}
  providerConfigRef:
    name: {{ $.Values.aws.providerConfigName }}
{{- end }}
{{- end }}
