{{- if .Values.aws.s3 }}
apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: {{ include "serverless-pdf-chat.resourceName" (dict "Values" .Values "name" "documents") }}
  labels:
    {{- include "serverless-pdf-chat.labels" . | nindent 4 }}
spec:
  forProvider:
    region: {{ .Values.aws.region }}
    {{- if .Values.aws.s3.documentBucketName }}
    bucket: {{ .Values.aws.s3.documentBucketName }}
    {{- else }}
    bucket: {{ include "serverless-pdf-chat.resourceName" (dict "Values" .Values "name" "documents") }}
    {{- end }}
    {{- with .Values.tags }}
    tags:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    force_destroy: true
    {{- if .Values.aws.s3.versioning }}
    versioning:
      enabled: true
    {{- end }}
    {{- if .Values.aws.s3.corsEnabled }}
    cors_rule:
      - allowed_headers:
          - "*"
        allowed_methods:
          - GET
          - PUT
          - POST
          - DELETE
          - HEAD
        allowed_origins:
          - "*"
        expose_headers:
          - ETag
        max_age_seconds: 3000
    {{- end }}
    server_side_encryption_configuration:
      rule:
        - apply_server_side_encryption_by_default:
            sse_algorithm: "AES256"
    {{- if .Values.aws.s3.lifecycleRules }}
    lifecycle_rule:
      {{- range .Values.aws.s3.lifecycleRules }}
      - enabled: {{ .enabled }}
        {{- if .expiration }}
        expiration:
          days: {{ .expiration }}
        {{- end }}
      {{- end }}
    {{- end }}
  providerConfigRef:
    name: {{ .Values.aws.providerConfigName }}
---
apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketPublicAccessBlock
metadata:
  name: {{ include "serverless-pdf-chat.resourceName" (dict "Values" .Values "name" "documents-public-access-block") }}
  labels:
    {{- include "serverless-pdf-chat.labels" . | nindent 4 }}
spec:
  forProvider:
    region: {{ .Values.aws.region }}
    bucket_ref:
      name: {{ include "serverless-pdf-chat.resourceName" (dict "Values" .Values "name" "documents") }}
    block_public_acls: {{ .Values.aws.s3.publicAccessBlockConfiguration.blockPublicAcls }}
    block_public_policy: {{ .Values.aws.s3.publicAccessBlockConfiguration.blockPublicPolicy }}
    ignore_public_acls: {{ .Values.aws.s3.publicAccessBlockConfiguration.ignorePublicAcls }}
    restrict_public_buckets: {{ .Values.aws.s3.publicAccessBlockConfiguration.restrictPublicBuckets }}
  providerConfigRef:
    name: {{ .Values.aws.providerConfigName }}
{{- end }}
