{{- if .Values.aws.sqs }}
{{- if .Values.aws.sqs.embeddingQueue }}
---
apiVersion: sqs.aws.upbound.io/v1beta1
kind: Queue
metadata:
  name: {{ include "serverless-pdf-chat.resourceName" (dict "Values" .Values "name" "embedding") }}
  labels:
    {{- include "serverless-pdf-chat.labels" $ | nindent 4 }}
spec:
  forProvider:
    region: {{ .Values.aws.region }}
    {{- if .Values.aws.sqs.embeddingQueue.name }}
    name: {{ .Values.aws.sqs.embeddingQueue.name }}
    {{- else }}
    name: {{ include "serverless-pdf-chat.resourceName" (dict "Values" .Values "name" "embedding") }}
    {{- end }}
    {{- with $.Values.tags }}
    tags:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    visibilityTimeoutSeconds: {{ .Values.aws.sqs.embeddingQueue.visibilityTimeout }}
    messageRetentionSeconds: {{ .Values.aws.sqs.embeddingQueue.messageRetentionPeriod }}
    delaySeconds: 0
  providerConfigRef:
    name: {{ $.Values.aws.providerConfigName }}
{{- end }}
{{- end }}
