apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "serverless-pdf-chat.fullname" . }}-wait-for-xrd
  labels:
    {{- include "serverless-pdf-chat.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "0"  # Run after the Composition but before the CognitoAuth
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "serverless-pdf-chat.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "serverless-pdf-chat.fullname" . }}-xrd-wait-sa
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command:
        - /bin/bash
        - -c
        - |
          echo "Waiting for CognitoAuth XRD to be ready..."
          until kubectl get crd cognitoauths.serverlesspdfchat.shortrib.io; do
            echo "Waiting for XRD..."
            sleep 2
          done
          echo "XRD is ready!"
      restartPolicy: OnFailure
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "serverless-pdf-chat.fullname" . }}-xrd-wait-sa
  labels:
    {{- include "serverless-pdf-chat.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "serverless-pdf-chat.fullname" . }}-xrd-wait-role
  labels:
    {{- include "serverless-pdf-chat.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: hook-succeeded
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "serverless-pdf-chat.fullname" . }}-xrd-wait-rolebinding
  labels:
    {{- include "serverless-pdf-chat.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: hook-succeeded
subjects:
- kind: ServiceAccount
  name: {{ include "serverless-pdf-chat.fullname" . }}-xrd-wait-sa
roleRef:
  kind: Role
  name: {{ include "serverless-pdf-chat.fullname" . }}-xrd-wait-role
  apiGroup: rbac.authorization.k8s.io
