apiVersion: apigatewayv2.aws.upbound.io/v1beta1
kind: Route
metadata:
  name: {{ include "serverless-pdf-chat.fullname" . }}-get-document-route
  labels:
    {{- include "serverless-pdf-chat.labels" . | nindent 4 }}
spec:
  forProvider:
    region: {{ .Values.aws.region }}
    api_id: {{ "{{" }} resolve:path:apiId {{ "}}" }}
    route_key: "GET /doc/{documentid}/{conversationid}"
    target: {{ "{{" }} resolve:path:target {{ "}}" }}
    authorization_type: JWT
    authorizer_id: {{ "{{" }} resolve:path:authorizerId {{ "}}" }}
  providerConfigRef:
    name: {{ .Values.aws.providerConfigName }}
  references:
    - apiId:
        from:
          apiRef:
            name: {{ include "serverless-pdf-chat.fullname" . }}-api
    - target:
        from:
          apiRef:
            name: {{ include "serverless-pdf-chat.fullname" . }}-get-document-integration
            path: forProvider.integrationId
    - authorizerId:
        from:
          apiRef:
            name: {{ include "serverless-pdf-chat.fullname" . }}-cognito-authorizer
            path: status.atProvider.id
