apiVersion: apigatewayv2.aws.upbound.io/v1beta1
kind: Route
metadata:
  name: {{ include "serverless-pdf-chat.fullname" . }}-get-document-route
  labels:
    {{- include "serverless-pdf-chat.labels" . | nindent 4 }}
spec:
  forProvider:
    region: {{ .Values.aws.region }}
    apiIdSelector:
      matchLabels:
        {{- include "serverless-pdf-chat.selectorLabels" . | nindent 8 }}
        api: {{ include "serverless-pdf-chat.fullname" . }}-api
    routeKey: "GET /doc/{documentid}/{conversationid}"
    targetSelector:
      matchLabels:
        {{- include "serverless-pdf-chat.selectorLabels" . | nindent 8 }}
        integration: {{ include "serverless-pdf-chat.fullname" . }}-get-document-integration
    authorizationType: JWT
    authorizerIdSelector:
      matchLabels:
        {{- include "serverless-pdf-chat.selectorLabels" . | nindent 8 }}
        authorizer: {{ include "serverless-pdf-chat.fullname" . }}-cognito-authorizer
  providerConfigRef:
    name: {{ .Values.aws.providerConfigName }}
