apiVersion: v2
name: serverless-pdf-chat
description: A Helm chart for deploying serverless PDF chat infrastructure
type: application
version: 0.12.1  # Bumped from 0.12.0 to 0.12.1 for fixing FrontendConfig selectors
appVersion: "1.0.0"  # This will be used for Docker image tags
