apiVersion: v2
name: serverless-pdf-chat
description: A Helm chart for deploying serverless PDF chat infrastructure
type: application
version: 0.8.3  # Bump from 0.8.2 to 0.8.3
appVersion: "1.0.0"  # This will be used for Docker image tags
