apiVersion: v2
name: serverless-pdf-chat
description: A Helm chart for deploying serverless PDF chat infrastructure
type: application
version: 0.5.1  # Bump from 0.5.0 to 0.5.1 (patch version for bug fix)
appVersion: "1.0.0"
