apiVersion: v2
name: serverless-pdf-chat
description: A Helm chart for deploying serverless PDF chat infrastructure
type: application
version: 0.11.1  # Bump from 0.11.0 to 0.11.1 for adding image pull secrets to frontend
appVersion: "1.0.0"  # This will be used for Docker image tags
