apiVersion: v2
name: serverless-pdf-chat
description: A Helm chart for deploying serverless PDF chat infrastructure
type: application
version: 0.11.2  # Bump from 0.11.1 to 0.11.2 for updating ECR authentication
appVersion: "1.0.0"  # This will be used for Docker image tags
