apiVersion: v2
name: serverless-pdf-chat
description: A Helm chart for deploying serverless PDF chat infrastructure
type: application
version: 0.5.0  # Bump from 0.4.5 to 0.5.0 (minor version bump for new feature)
appVersion: "1.0.0"
