apiVersion: v2
name: serverless-pdf-chat
description: A Helm chart for deploying serverless PDF chat infrastructure
type: application
version: 0.10.7  # Bumped version from 0.10.6 to 0.10.7
appVersion: "1.0.0"  # This will be used for Docker image tags
