apiVersion: v2
name: serverless-pdf-chat
description: A Helm chart for deploying serverless PDF chat infrastructure
type: application
version: 0.10.5  # Bumped version
appVersion: "1.0.0"  # This will be used for Docker image tags
