# Default values for serverless-pdf-chat
# This is a YAML-formatted file.

global:
  namePrefix: "pdf-chat"
  environment: "dev"

aws:
  region: "us-west-2"
  accountId: "123456789012"  # This should be replaced with the actual AWS account ID
  providerConfigName: "default"
  s3:
    documentBucketName: null
    corsEnabled: true
    versioning: true
    lifecycleRules:
      - enabled: true
        expiration: 90
    publicAccessBlockConfiguration:
      blockPublicAcls: true
      blockPublicPolicy: true
      ignorePublicAcls: true
      restrictPublicBuckets: true
        
  dynamodb:
    billingMode: "PAY_PER_REQUEST"
    documentTable:
      name: null
    memoryTable:
      name: null
        
  sqs:
    embeddingQueue:
      name: null
      visibilityTimeout: 180
      messageRetentionPeriod: 3600
  
  cognito:
    userPool:
      name: null
      autoVerifiedAttributes: ["email"]
      usernameAttributes: ["email"]
      adminCreateUserConfig:
        allowAdminCreateUserOnly: true
      passwordPolicy:
        minimumLength: 8
        requireLowercase: true
        requireNumbers: true
        requireSymbols: true
        requireUppercase: true
    userPoolClient:
      name: null
      generateSecret: false
  
  iam:
    roles:
      lambdaRole:
        name: null  # Optional, will use a generated name if not provided
        policies:
          name: null  # Optional, will use a default name if not provided
        
tags:
  environment: "dev"
  application: "pdf-chat"
