apiVersion: apigatewayv2.aws.upbound.io/v1beta1
kind: Authorizer
metadata:
  name: {{ include "serverless-pdf-chat.fullname" . }}-cognito-authorizer
  labels:
    {{- include "serverless-pdf-chat.labels" . | nindent 4 }}
    authorizer: {{ include "serverless-pdf-chat.fullname" . }}-cognito-authorizer
spec:
  forProvider:
    region: {{ .Values.aws.region }}
    apiIdSelector:
      matchLabels:
        {{- include "serverless-pdf-chat.selectorLabels" . | nindent 8 }}
        api: {{ include "serverless-pdf-chat.fullname" . }}-api
    name: {{ include "serverless-pdf-chat.fullname" . }}-cognito-authorizer
    authorizerType: JWT
    identitySource:
      - "$request.header.Authorization"
    jwtConfiguration:
      audiences:
        - selector:
            matchLabels:
              {{- include "serverless-pdf-chat.selectorLabels" . | nindent 14 }}
              client: {{ include "serverless-pdf-chat.fullname" . }}-user-pool-client
      issuer: 
        selector:
          matchLabels:
            {{- include "serverless-pdf-chat.selectorLabels" . | nindent 12 }}
            pool: {{ include "serverless-pdf-chat.fullname" . }}-user-pool
  providerConfigRef:
    name: {{ .Values.aws.providerConfigName }}
