apiVersion: apigatewayv2.aws.upbound.io/v1beta1
kind: Authorizer
metadata:
  name: {{ include "serverless-pdf-chat.fullname" . }}-cognito-authorizer
  labels:
    {{- include "serverless-pdf-chat.labels" . | nindent 4 }}
spec:
  forProvider:
    region: {{ .Values.aws.region }}
    apiIdSelector:
      matchLabels:
        {{- include "serverless-pdf-chat.selectorLabels" . | nindent 8 }}
        api: {{ include "serverless-pdf-chat.fullname" . }}-api
    name: CognitoAuthorizer
    authorizerType: JWT
    identitySources:
      - "$request.header.Authorization"
    jwtConfiguration:
      audience:
        - "{{ "{{" }} resolve:path:clientId {{ "}}" }}"
      issuer: "{{ "{{" }} resolve:path:issuer {{ "}}" }}"
  providerConfigRef:
    name: {{ .Values.aws.providerConfigName }}
  references:
    - clientId:
        from:
          apiRef:
            name: {{ include "serverless-pdf-chat.fullname" . }}-user-pool-client
    - issuer:
        from:
          apiRef:
            name: {{ include "serverless-pdf-chat.fullname" . }}-user-pool
            path: forProvider.endpoint
