apiVersion: apigatewayv2.aws.upbound.io/v1beta1
kind: Authorizer
metadata:
  name: {{ include "serverless-pdf-chat.fullname" . }}-cognito-authorizer
  labels:
    {{- include "serverless-pdf-chat.labels" . | nindent 4 }}
spec:
  forProvider:
    region: {{ .Values.aws.region }}
    apiId: {{ "{{" }} resolve:path:apiId {{ "}}" }}
    name: CognitoAuthorizer
    authorizerType: JWT
    identitySources:
      - "$request.header.Authorization"
    jwtConfiguration:
      audiences:
        - {{ "{{" }} resolve:path:clientId {{ "}}" }}
      issuer: {{ "{{" }} resolve:path:issuer {{ "}}" }}
  providerConfigRef:
    name: {{ .Values.aws.providerConfigName }}
  references:
    - apiId:
        from:
          apiRef:
            name: {{ include "serverless-pdf-chat.fullname" . }}-api
    - clientId:
        from:
          apiRef:
            name: {{ include "serverless-pdf-chat.fullname" . }}-user-pool-client
    - issuer:
        from:
          apiRef:
            name: {{ include "serverless-pdf-chat.fullname" . }}-user-pool
            path: forProvider.endpoint
