apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: cognitoauths.serverlesspdfchat.shortrib.io
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"  # Run after wait-ready-job (weight 0)
spec:
  group: serverlesspdfchat.shortrib.io
  names:
    kind: CognitoAuth
    plural: cognitoauths
  claimNames:
    kind: CognitoAuthClaim
    plural: cognitoauthclaims
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                region:
                  type: string
                  description: "AWS region"
                providerConfigRef:
                  type: object
                  description: "Reference to the provider configuration"
                  properties:
                    name:
                      type: string
                apiIdSelector:
                  type: object
                  description: "Selector for the API Gateway API"
                  properties:
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
                userPoolName:
                  type: string
                  description: "Name of the Cognito User Pool"
                userPoolClientName:
                  type: string
                  description: "Name of the Cognito User Pool Client"
                authorizerName:
                  type: string
                  description: "Name of the API Gateway Authorizer"
                tags:
                  type: object
                  description: "Tags to apply to all resources"
                  additionalProperties:
                    type: string
              required:
                - region
                - apiIdSelector
                - userPoolName
                - userPoolClientName
                - authorizerName
            status:
              type: object
              properties:
                atProvider:
                  type: object
                  description: "Provider-specific status fields"
                  x-kubernetes-preserve-unknown-fields: true
                userPoolId:
                  type: string
                  description: "ID of the created Cognito User Pool"
                userPoolClientId:
                  type: string
                  description: "ID of the created Cognito User Pool Client"
                authorizerId:
                  type: string
                  description: "ID of the created API Gateway Authorizer"
