apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "providers.fullname" . }}-cleanup
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    metadata:
      name: {{ include "providers.fullname" . }}-cleanup
    spec:
      serviceAccountName: {{ include "providers.fullname" . }}-jobs
      restartPolicy: Never
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          # Delete providers
          {{- range $key, $value := .Values.aws.providers }}
          {{- if ne $key "registry" }}
          kubectl delete provider.pkg.crossplane.io {{ include "providers.fullname" $ }}-aws-{{ $key }} --ignore-not-found
          {{- end }}
          {{- end }}
          
          # Delete kubernetes provider
          kubectl delete provider.pkg.crossplane.io {{ include "providers.fullname" $ }}-kubernetes --ignore-not-found
          
          # Wait for cleanup to complete
          sleep 10
