apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: {{ .Values.aws.providerConfigName }}
spec:
  credentials:
    source: {{ .Values.aws.authentication.method | camelcase }}
    {{- if eq .Values.aws.authentication.method "Secret" }}
    secretRef:
      namespace: {{ include "crossplane-providers.secretNamespace" . }}
      name: {{ include "crossplane-providers.secretName" . }}
      key: {{ include "crossplane-providers.secretKey" . }}
    {{- end }}
  region: {{ .Values.aws.region }}
