{{- if eq .Values.aws.authentication.method "secret" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crossplane-providers.secretName" . }}
  namespace: {{ include "crossplane-providers.secretNamespace" . }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
stringData:
  {{ include "crossplane-providers.secretKey" . }}: |
    [default]
    aws_access_key_id = ${AWS_ACCESS_KEY_ID}
    aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}
{{- end }}
