{{- if eq .Values.aws.authentication.method "secret" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.aws.authentication.secret.name }}
  namespace: {{ .Values.aws.authentication.secret.namespace }}
type: Opaque
stringData:
  creds: |
    [default]
    aws_access_key_id = ${AWS_ACCESS_KEY_ID}
    aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}
{{- end }}
