{{- $functionName := "generate-response" -}}
{{- $functionConfig := index .Values.aws.lambda.functions "generateResponse" -}}
{{- template "serverless-pdf-chat.lambda-function" (dict "Values" .Values "Release" .Release "Chart" .Chart "functionName" $functionName "functionConfig" $functionConfig) -}}
