{{- $functionName := "generate-presigned-url" -}}
{{- $functionCamelCase := "generatePresignedUrl" -}}
{{- $functionConfig := index .Values.aws.lambda.functions $functionCamelCase -}}
{{- include "serverless-pdf-chat.lambda-function" (dict "Values" .Values "Release" .Release "Chart" .Chart "functionName" $functionName "functionCamelCase" $functionCamelCase "functionConfig" $functionConfig) -}}
