{{- $functionName := "generate-response" -}}
{{- $functionCamelCase := "generateResponse" -}}
{{- $functionConfig := index .Values.aws.lambda.functions $functionCamelCase -}}
{{- template "serverless-pdf-chat.lambda-function" (dict "Values" .Values "Release" .Release "Chart" .Chart "functionName" $functionName "functionCamelCase" $functionCamelCase "functionConfig" $functionConfig) -}}
