{{- $functionName := "generate-presigned-url" -}}
{{- $functionConfig := index .Values.aws.lambda.functions "generatePresignedUrl" -}}
{{- template "serverless-pdf-chat.lambda-function" (dict "Values" .Values "Release" .Release "Chart" .Chart "functionName" $functionName "functionConfig" $functionConfig) -}}
