{{- $functions := list "upload_trigger" "generate_presigned_url" "generate_embeddings" "get_document" "get_all_documents" "delete_document" "add_conversation" "generate_response" }}
{{- range $functions }}
{{- $functionName := . }}
{{- $dashFunctionName := $functionName | replace "_" "-" }}
apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketObject
metadata:
  name: {{ include "serverless-pdf-chat.fullname" $ }}-{{ $dashFunctionName }}-code
  labels:
    {{- include "serverless-pdf-chat.labels" $ | nindent 4 }}
spec:
  forProvider:
    region: {{ $.Values.aws.region }}
    bucket: {{ include "serverless-pdf-chat.bucketName" $ }}
    key: {{ printf "lambda/%s.zip" $functionName }}
    contentBase64: {{ $.Files.Get (printf "lambdas/%s.zip" $functionName) | b64enc }}
    contentType: "application/zip"
    acl: "private"
    forceDestroy: true
    tags:
      app: {{ include "serverless-pdf-chat.name" $ }}
      function: {{ $functionName }}
      {{- with $.Values.tags }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  providerConfigRef:
    name: {{ $.Values.aws.providerConfigName }}
---
{{- end }}
