{{- if and .Values.frontend.enabled .Values.frontend.image.pullSecretData }}
{{- range .Values.frontend.image.pullSecretData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    {{- include "serverless-pdf-chat.labels" $ | nindent 4 }}
    app.kubernetes.io/component: frontend
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .dockerconfigjson }}
---
{{- end }}
{{- end }}
