aws:
  # AWS region where resources will be provisioned
  region: "us-west-2"
  # Name of the provider configuration
  providerConfigName: "default"
  # Authentication settings for AWS
  authentication:
    # Method to authenticate with AWS (secret, irsa, or ec2)
    method: "secret"
    # Secret configuration when using secret authentication method
    secret:
      # Name of the secret containing AWS credentials
      name: "aws-credentials"
      # Namespace where the secret is located
      namespace: "crossplane-system"
      # Keys in the secret for AWS credentials
      keys:
        # Key for AWS access key ID
        accessKeyId: "aws_access_key_id"
        # Key for AWS secret access key
        secretAccessKey: "aws_secret_access_key"
  # AWS provider configurations
  providers:
    iam:
      version: "v0.41.0"
      controllerConfig: {}
    s3:
      version: "v0.41.0"
      controllerConfig: {}
    dynamodb:
      version: "v0.41.0"
      controllerConfig: {}
    lambda:
      version: "v0.41.0"
      controllerConfig: {}
    sqs:
      version: "v0.41.0"
      controllerConfig: {}
    apigateway:
      version: "v0.41.0"
      controllerConfig: {}
    cognito:
      version: "v0.41.0"
      controllerConfig: {}
    bedrock:
      version: "v0.41.0"
      controllerConfig: {}
    cloudfront:
      version: "v0.41.0"
      controllerConfig: {}
    secretsmanager:
      version: "v0.41.0"
      controllerConfig: {}
