apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: {{ include "crossplane-providers.fullname" . }}-aws-iam
  labels:
    {{- include "crossplane-providers.labels" . | nindent 4 }}
spec:
  package: xpkg.upbound.io/upbound/provider-aws-iam:{{ .Values.aws.providers.iam.version }}
  {{- if .Values.aws.providers.iam.controllerConfig }}
  controllerConfigRef:
    name: {{ .Values.aws.providers.iam.controllerConfig.name }}
  {{- end }}
