apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: {{ include "crossplane-providers.fullname" . }}-aws-bedrock
  labels:
    {{- include "crossplane-providers.labels" . | nindent 4 }}
spec:
  package: {{ include "crossplane-providers.packageUrl" (dict "Values" .Values "providerName" "bedrock") }}
  {{- if .Values.aws.providers.bedrock.controllerConfig }}
  controllerConfigRef:
    name: {{ .Values.aws.providers.bedrock.controllerConfig.name }}
  {{- end }}
